package org.pgist.packages;

import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;


/**
 * DWR AJAX Agent class for packages.
 * 
 * @author kenny
 *
 */
public class PackageAgent {
    
    
    private PackageService packageService;
    
    
    public void setPackageService(PackageService packageService) {
        this.packageService = packageService;
    }
    
    
    /*
     * ------------------------------------------------------------------------
     */
    
    
    /**
     * Set (Add/Delete) a project from a user package for the current participant
     * 
     * @param params a Map contains:<br>
     *   <ul>
     *     <li>pkgId - int, id of the UserPackage object</li>
     *     <li>altId - int, id of the ProjectAlternative object</li>
     *     <li>deleting - boolean, true | false. If deleting==true, delete the project alternative
     *         from package, else add the project alternative to package, default is "false".
     *     </li>
     *   </ul>
     *   
     * @return a Map contains:<br>
     *   <ul>
     *     <li>successful - a boolean value denoting if the operation succeeds</li>
     *     <li>reason - reason why operation failed (valid when successful==false)</li>
     *     <li>
     *       html - string, html source segment generated by "/WEB-INF/jsp/packages/createPackage_summary.jsp". In this page the following variables are avaiable:<br>
     *         <ul>
     *           <li>package - a UserPackage object</li>
     *           <li>stat - a PackageStat object</li>
     *         </ul>
     *     </li>
     *   </ul>
     */
    public Map setProjectToUserPkg(HttpServletRequest request, Map params) {
        Map map = new HashMap();
        map.put("successful", false);
        
        try {
            /*
             * TODO: persist the association
             */
            
            map.put("successful", true);
        } catch (Exception e) {
            e.printStackTrace();
            map.put("reason", e.getMessage());
            return map;
        }
        
        return map;
    }//setProjectToUserPkg()
    
    
    /**
     * Set (Add/Delete) a funding source from a user package for the current participant
     * 
     * @param params a Map contains:<br>
     *   <ul>
     *     <li>pkgId - int, id of the UserPackage object</li>
     *     <li>altId - int, id of the FundingAlternative object</li>
     *     <li>deleting - boolean, true | false. If deleting==true, delete the funding source alternative
     *         from package, else add the funding source alternative to package
     *     </li>
     *   </ul>
     *   
     * @return a Map contains:<br>
     *   <ul>
     *     <li>successful - a boolean value denoting if the operation succeeds</li>
     *     <li>reason - reason why operation failed (valid when successful==false)</li>
     *     <li>
     *       html - string, html source segment generated by "/WEB-INF/jsp/packages/createPackage_summary.jsp". In this page the following variables are avaiable:<br>
     *         <ul>
     *           <li>package - a UserPackage object</li>
     *           <li>stat - a PackageStat object</li>
     *         </ul>
     *     </li>
     *   </ul>
     */
    public Map setFundingToUserPkg(Map params) {
        Map map = new HashMap();
        map.put("successful", false);
        
        try {
            /*
             * TODO: persist the association
             */
            
            map.put("successful", true);
        } catch (Exception e) {
            e.printStackTrace();
            map.put("reason", e.getMessage());
            return map;
        }
        
        return map;
    }//setFundingToUserPkg()
    
    
    /**
     * Set (Add/Delete) a project from a clustered package for the current participant
     * 
     * @param params a Map contains:<br>
     *   <ul>
     *     <li>pkgId - int, id of the ClusteredPackage object</li>
     *     <li>altId - int, id of the ProjectAlternative object</li>
     *     <li>deleting - boolean, true | false. If deleting==true, delete the project alternative
     *         from package, else add the project alternative to package
     *     </li>
     *   </ul>
     *   
     * @return a Map contains:<br>
     *   <ul>
     *     <li>successful - a boolean value denoting if the operation succeeds</li>
     *     <li>reason - reason why operation failed (valid when successful==false)</li>
     *     <li>
     *       html - string, html source segment generated by "/WEB-INF/jsp/packages/createPackage_clusteredSummary.jsp". In this page the following variables are avaiable:<br>
     *         <ul>
     *           <li>package - a ClusteredPackage object</li>
     *           <li>stat - a PackageStat object</li>
     *         </ul>
     *     </li>
     *   </ul>
     */
    public Map setProjectToClusteredPkg(HttpServletRequest request, Map params) {
        Map map = new HashMap();
        map.put("successful", false);
        
        try {
            /*
             * TODO: persist the association
             */
            
            map.put("successful", true);
        } catch (Exception e) {
            e.printStackTrace();
            map.put("reason", e.getMessage());
            return map;
        }
        
        return map;
    }//setProjectToClusteredPkg()
    
    
    /**
     * Set (Add/Delete) a funding source from a clustered package for the current participant
     * 
     * @param params a Map contains:<br>
     *   <ul>
     *     <li>pkgId - int, id of the ClusteredPackage object</li>
     *     <li>altId - int, id of the FundingAlternative object</li>
     *     <li>deleting - boolean, true | false. If deleting==true, delete the funding source alternative
     *         from package, else add the funding source alternative to package
     *     </li>
     *   </ul>
     *   
     * @return a Map contains:<br>
     *   <ul>
     *     <li>successful - a boolean value denoting if the operation succeeds</li>
     *     <li>reason - reason why operation failed (valid when successful==false)</li>
     *     <li>
     *       html - string, html source segment generated by "/WEB-INF/jsp/packages/createPackage_clusteredSummary.jsp". In this page the following variables are avaiable:<br>
     *         <ul>
     *           <li>package - a ClusteredPackage object</li>
     *           <li>stat - a PackageStat object</li>
     *         </ul>
     *     </li>
     *   </ul>
     */
    public Map setFundingToClusteredPkg(Map params) {
        Map map = new HashMap();
        map.put("successful", false);
        
        try {
            /*
             * TODO: persist the association
             */
            
            map.put("successful", true);
        } catch (Exception e) {
            e.printStackTrace();
            map.put("reason", e.getMessage());
            return map;
        }
        
        return map;
    }//setFundingToClusteredPkg()
    
    
    /**
     * Set the voting selection for the current user.
     * 
     * @param params A map contains:
     *     <ul>
     *       <li>suiteId - int, id for a PackageVoteSuite object</li>
     *       <li>vote - int, vote value, [0 | 1 | 2 | 3]
     *         <ul>
     *           <li>0 - unknown</li> 
     *           <li>1 - High</li> 
     *           <li>2 - Medium</li> 
     *           <li>3 - Low</li> 
     *         </ul> 
     *       </li>
     *     </ul>
     * 
     * @return A map contains:
     *   <ul>
     *     <li>successful - a boolean value denoting if the operation succeeds</li>
     *     <li>reason - reason why operation failed (valid when successful==false)</li>
     *   </ul>
     */
    public Map setVoting(Map params) {
        Map map = new HashMap();
        map.put("successful", false);
        
        try {
            /*
             * TODO: persist the voting selection
             */
            
            map.put("successful", true);
        } catch (Exception e) {
            e.printStackTrace();
            map.put("reason", e.getMessage());
            return map;
        }
        
        return map;
    }//setVoting()
    
    
    /**
     * Create a new clustered package in a specified PackageSuite.
     * 
     * @param params A map contains:
     *     <ul>
     *       <li>suiteId - int, id for a PackageSuite object</li>
     *       <li>description - string</li>
     *     </ul>
     *     
     * @returnA A map contains:
     *   <ul>
     *     <li>successful - a boolean value denoting if the operation succeeds</li>
     *     <li>reason - reason why operation failed (valid when successful==false)</li>
     *     <li>pkgId - int, the newly created package id (valid when successful==false)</li>
     *   </ul>
     */
    public Map createClusteredPackage(Map params) {
        Map map = new HashMap();
        map.put("successful", false);
        
        try {
            /*
             * TODO: create a new ClusteredPackage
             */
            
            map.put("successful", true);
        } catch (Exception e) {
            e.printStackTrace();
            map.put("reason", e.getMessage());
            return map;
        }
        
        return map;
    }//createClusteredPackage()
    
    
    /**
     * Delete a specified clustered package from a PackageSuite.
     * 
     * @param params A map contains:
     *     <ul>
     *       <li>suiteId - int, id for a PackageSuite object</li>
     *       <li>pkgId - int, id for a ClusteredPackage object</li>
     *     </ul>
     *     
     * @returnA A map contains:
     *     <ul>
     *       <li></li>
     *     </ul>
     */
    public Map deleteClusteredPackage(Map params) {
        Map map = new HashMap();
        map.put("successful", false);
        
        try {
            /*
             * TODO: delete the specified package
             */
            
            map.put("successful", true);
        } catch (Exception e) {
            e.printStackTrace();
            map.put("reason", e.getMessage());
            return map;
        }
        
        return map;
    }//deleteClusteredPackage()
    
    
}//class PackageAgent
