package org.pgist.packages;

import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;


/**
 * 
 * @author kenny
 *
 */
public class PackageAgent {
    
    
    private PackageService packageService;
    
    
    public void setPackageService(PackageService packageService) {
        this.packageService = packageService;
    }
    
    
    /*
     * ------------------------------------------------------------------------
     */
    
    
    /**
     * Set (Add/Delete) a project from a user package for the current participant
     * 
     * @param params a Map contains:<br>
     *   <ul>
     *     <li>pkgId - int, id of the UserPackage object</li>
     *     <li>altId - int, id of the ProjectAlternative object</li>
     *     <li>deleting - boolean, true | false. If deleting==true, delete the project alternative
     *         from package, else add the project alternative to package, default is "false".
     *     </li>
     *   </ul>
     *   
     * @return a Map contains:<br>
     *   <ul>
     *     <li>successful - a boolean value denoting if the operation succeeds</li>
     *     <li>reason - reason why operation failed (valid when successful==false)</li>
     *     <li>
     *       html - string, html source segment generated by "/WEB-INF/jsp/packages/createPackage_summary.jsp". In this page the following variables are avaiable:<br>
     *         <ul>
     *           <li>package - a UserPackage object</li>
     *           <li>stat - a PackageStat object</li>
     *         </ul>
     *     </li>
     *   </ul>
     */
    public Map setProjectToPkg(HttpServletRequest request, Map params) {
        Map map = new HashMap();
        map.put("successful", false);
        
        try {
            
            map.put("successful", true);
        } catch (Exception e) {
            e.printStackTrace();
            map.put("reason", e.getMessage());
            return map;
        }
        
        return map;
    }//setProjectToPkg()
    
    
    /**
     * Set (Add/Delete) a funding source from a user package for the current participant
     * 
     * @param params a Map contains:<br>
     *   <ul>
     *     <li>pkgId - int, id of the UserPackage object</li>
     *     <li>altId - int, id of the FundingAlternative object</li>
     *     <li>deleting - boolean, true | false. If deleting==true, delete the funding source alternative
     *         from package, else add the funding source alternative to package
     *     </li>
     *   </ul>
     *   
     * @return a Map contains:<br>
     *   <ul>
     *     <li>successful - a boolean value denoting if the operation succeeds</li>
     *     <li>reason - reason why operation failed (valid when successful==false)</li>
     *     <li>
     *       html - string, html source segment generated by "/WEB-INF/jsp/packages/createPackage_summary.jsp". In this page the following variables are avaiable:<br>
     *         <ul>
     *           <li>package - a UserPackage object</li>
     *           <li>stat - a PackageStat object</li>
     *         </ul>
     *     </li>
     *   </ul>
     */
    public Map setFundingToPkg(Map params) {
        Map map = new HashMap();
        map.put("successful", false);
        
        try {
            
            map.put("successful", true);
        } catch (Exception e) {
            e.printStackTrace();
            map.put("reason", e.getMessage());
            return map;
        }
        
        return map;
    }//setFundingToPkg()
    
    
    /**
     * Set (Add/Delete) a project from a clustered package for the current participant
     * 
     * @param params a Map contains:<br>
     *   <ul>
     *     <li>pkgId - int, id of the ClusteredPackage object</li>
     *     <li>altId - int, id of the ProjectAlternative object</li>
     *     <li>deleting - boolean, true | false. If deleting==true, delete the project alternative
     *         from package, else add the project alternative to package
     *     </li>
     *   </ul>
     *   
     * @return a Map contains:<br>
     *   <ul>
     *     <li>successful - a boolean value denoting if the operation succeeds</li>
     *     <li>reason - reason why operation failed (valid when successful==false)</li>
     *     <li>
     *       html - string, html source segment generated by "/WEB-INF/jsp/packages/createPackage_clusteredSummary.jsp". In this page the following variables are avaiable:<br>
     *         <ul>
     *           <li>package - a ClusteredPackage object</li>
     *           <li>stat - a PackageStat object</li>
     *         </ul>
     *     </li>
     *   </ul>
     */
    public Map setProjectToClusteredPkg(HttpServletRequest request, Map params) {
        Map map = new HashMap();
        map.put("successful", false);
        
        try {
            
            map.put("successful", true);
        } catch (Exception e) {
            e.printStackTrace();
            map.put("reason", e.getMessage());
            return map;
        }
        
        return map;
    }//setProjectToClusteredPkg()
    
    
    /**
     * Set (Add/Delete) a funding source from a clustered package for the current participant
     * 
     * @param params a Map contains:<br>
     *   <ul>
     *     <li>pkgId - int, id of the ClusteredPackage object</li>
     *     <li>altId - int, id of the FundingAlternative object</li>
     *     <li>deleting - boolean, true | false. If deleting==true, delete the funding source alternative
     *         from package, else add the funding source alternative to package
     *     </li>
     *   </ul>
     *   
     * @return a Map contains:<br>
     *   <ul>
     *     <li>successful - a boolean value denoting if the operation succeeds</li>
     *     <li>reason - reason why operation failed (valid when successful==false)</li>
     *     <li>
     *       html - string, html source segment generated by "/WEB-INF/jsp/packages/createPackage_clusteredSummary.jsp". In this page the following variables are avaiable:<br>
     *         <ul>
     *           <li>package - a ClusteredPackage object</li>
     *           <li>stat - a PackageStat object</li>
     *         </ul>
     *     </li>
     *   </ul>
     */
    public Map setFundingToClusteredPkg(Map params) {
        Map map = new HashMap();
        map.put("successful", false);
        
        try {
            
            map.put("successful", true);
        } catch (Exception e) {
            e.printStackTrace();
            map.put("reason", e.getMessage());
            return map;
        }
        
        return map;
    }//setFundingToClusteredPkg()
    
    
}//class PackageAgent
