package org.pgist.projects;

import java.sql.Connection;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import org.apache.commons.collections.map.HashedMap;
import org.directwebremoting.WebContextFactory;


/**
 * @author Guirong
 */
public class ProjectAgent {
    
    
	private ProjectService projectService = null;
	
    
	/**
     * This is not an AJAX method
     * @param ps
     */
	public void setProjectService(ProjectService ps){
        this.projectService = ps;
    }


	/*
     * ------------------------------------------------------------------------
	 */
    
    
    /**
     * Get a Project object by id
     *
     * @param  A map contains:
     *     <ul>
     *       <li>id - int, id of the Project object</li>
     *     </ul>
     * 
     * @return A map contains:
     *     <ul>
     *       <li>successful - a boolean value denoting if the operation succeeds</li>
     *       <li>reason - reason why operation failed (valid when successful==false)</li>
     *       <li>project - a Project object</li>
     *     </ul>
     */
    public Map getProjectById(Map params) {
        Map map = new HashMap();
        map.put("successful", false);
        
        try {
            Long id = new Long((String) params.get("id"));
            Project project = projectService.getProjectById(id);
            map.put("project", project);
        } catch (Exception e) {
            e.printStackTrace();
            map.put("reason", e.getMessage());
        }
        
        return map;
    }//getProjectById()
    
    
    /**
     * Get a ProjectAlternative object by id
     *
     * @param  A map contains:
     *     <ul>
     *       <li>id - int, id of the ProjectAlternative object</li>
     *     </ul>
     * 
     * @return A map contains:
     *     <ul>
     *       <li>successful - a boolean value denoting if the operation succeeds</li>
     *       <li>reason - reason why operation failed (valid when successful==false)</li>
     *       <li>alternative - a ProjectAlternative object</li>
     *     </ul>
     */
    public Map getProjectAlternativeById(Map params) {
        Map map = new HashMap();
        map.put("successful", false);
        
        try {
            Long id = new Long((String) params.get("id"));
            ProjectAlternative alternative = projectService.getProjectAlternativeById(id);
            map.put("alternative", alternative);
        } catch (Exception e) {
            e.printStackTrace();
            map.put("reason", e.getMessage());
        }
        
        return map;
    }//getProjectAlternativeById()
    
    
    /**
     * Get a page segment of projects list for project management.<br>
     * 
     * @param params A empty map
     * 
     * @return A map contains:
     *     <ul>
     *       <li>successful - a boolean value denoting if the operation succeeds</li>
     *       <li>reason - reason why operation failed (valid when successful==false)</li>
     *       <li>
     *         html - string, html source segment generated by "/WEB-INF/jsp/projects/projectMgr_projects.jsp". In this page the following variables are avaiable:<br>
     *           <ul>
     *             <li>projects - a list of Project objects</li>
     *           </ul>
     *       </li>
     *     </ul>
     */
    public Map getProjectsForMgr(HttpServletRequest request, Map params){
        Map map = new HashedMap();
        map.put("successful", false);
        
        try{
            /*
             * Get all the projects
             */
            Collection projects = projectService.getProjects();
            
            request.setAttribute("projects", projects);
            
            map.put("html", WebContextFactory.get().forwardToString("/WEB-INF/jsp/projects/projectMgr_projects.jsp"));
            
            map.put("successful", true);
        }catch(Exception e){
            e.printStackTrace();
            map.put("reason", e.getMessage());
        }
        
        return map;
    }//getProjectsForMgr()
    
    
    /**
     * Create a new Project with the given information.
     * 
     * @param params A map contains:
     *     <ul>
     *       <li>name - string, name of the Project object</li>
     *       <li>description - string, description of the project</li>
     *       <li>transMode - int, 1 for "road", 2 for "transit"</li>
     *     </ul>
     * 
     * @return A map contains:
     *     <ul>
     *       <li>successful - a boolean value denoting if the operation succeeds</li>
     *       <li>reason - reason why operation failed (valid when successful==false)</li>
     *       <li>id - the id of the new Project object</li>
     *     </ul>
     */
    public Map createProject(Map params) {
        Map map = new HashMap();
        map.put("successful", false);
        
        try {
            String name = (String) params.get("name");
            String description = (String) params.get("description");
            int transMode = Integer.parseInt((String) params.get("transMode"));
            
            Project project = projectService.createProject(name, description, transMode);
            
            map.put("id", project.getId());
            
            map.put("successful", true);
        } catch (Exception e) {
            e.printStackTrace();
            map.put("reason", e.getMessage());
            return map;
        }
        
        return map;
    }//createProject()
    
    
    /**
     * Create a new Project Alt with the given information.
     * 
     * @param params A map contains:
     *     <ul>
     *       <li>id - int, id of a Project object</li>
     *       <li>name - string, name for ProjectAlternative</li>
     *       <li>description - string, description for ProjectAlternative</li>
     *       <li>cost - float, cost</li>
     *       <li>links - string, links</li>
     *       <li>sponsor - string, name of sponsor</li>
     *       <li>statementFor - string</li>
     *       <li>statementAgainst - string</li>
     *     </ul>
     * 
     * @return A map contains:
     *     <ul>
     *       <li>successful - a boolean value denoting if the operation succeeds</li>
     *       <li>reason - reason why operation failed (valid when successful==false)</li>
     *       <li>id - the id of the new ProjectAlternative object</li>
     *     </ul>
     */
    public Map createProjectAlt(Map params) {
        Map map = new HashMap();
        map.put("successful", false);
        
        try {
            Long id = new Long((String) params.get("id"));
            
            ProjectAlternative projectAlt = projectService.createProjectAlt(id, params);
            
            map.put("id", projectAlt.getId());
            
            map.put("successful", true);
        } catch (Exception e) {
            e.printStackTrace();
            map.put("reason", e.getMessage());
        }
        
        return map;
    }//createProjectAlt()
    
    
    /**
     * Edit a Project object with the given information.
     * 
     * @param params A map contains:
     *     <ul>
     *       <li>id - int, id of the Project object</li>
     *       <li>name - string, name of the Project object</li>
     *       <li>description - string, description of the project</li>
     *       <li>transMode - int, 1 for "road", 2 for "transit"</li>
     *     </ul>
     * 
     * @return A map contains:
     *     <ul>
     *       <li>successful - a boolean value denoting if the operation succeeds</li>
     *       <li>reason - reason why operation failed (valid when successful==false)</li>
     *     </ul>
     */
    public Map editProject(Map params) {
        Map map = new HashMap();
        map.put("successful", false);
        
        try {
            Long id = new Long((String) params.get("id"));
            String name = (String) params.get("name");
            String description = (String) params.get("description");
            int transMode = Integer.parseInt((String) params.get("transMode"));
            
            projectService.editProject(id, name, description, transMode);
            
            map.put("successful", true);
        } catch (Exception e) {
            e.printStackTrace();
            map.put("reason", e.getMessage());
            return map;
        }
        
        return map;
    }//editProject()
    
    
    /**
     * Edit a Project Alt with the given information.
     * 
     * @param params A map contains:
     *     <ul>
     *       <li>id - int, id of a ProjectAlternative object</li>
     *       <li>name - string, name for ProjectAlternative</li>
     *       <li>description - string, description for ProjectAlternative</li>
     *       <li>cost - float, cost</li>
     *       <li>links - string, links</li>
     *       <li>sponsor - string, name of sponsor</li>
     *       <li>statementFor - string</li>
     *       <li>statementAgainst - string</li>
     *     </ul>
     * 
     * @return A map contains:
     *     <ul>
     *       <li>successful - a boolean value denoting if the operation succeeds</li>
     *       <li>reason - reason why operation failed (valid when successful==false)</li>
     *     </ul>
     */
    public Map editProjectAlt(Map params, double[][][] footprint) {
        Map map = new HashMap();
        map.put("successful", false);
        
        try {
            Long id = new Long((String) params.get("id"));
            
            projectService.editProjectAlt(id, params);
            
            map.put("successful", true);
        } catch (Exception e) {
            e.printStackTrace();
            map.put("reason", e.getMessage());
        }
        
        return map;
    }//editProjectAlt()
    
    
    /**
     * Delete a Project.
     * 
     * @param params A map contains:
     *     <ul>
     *       <li>id - int, id of a Project object</li>
     *     </ul>
     * 
     * @return A map contains:
     *     <ul>
     *       <li>successful - a boolean value denoting if the operation succeeds</li>
     *       <li>reason - reason why operation failed (valid when successful==false)</li>
     *     </ul>
     */
    public Map deleteProject(Map params) {
        Map map = new HashMap();
        map.put("successful", false);
        
        try {
            Long id = new Long((String) params.get("id"));
            
            projectService.deleteProject(id);
            
            map.put("successful", true);
        } catch (Exception e) {
            e.printStackTrace();
            map.put("reason", e.getMessage());
            return map;
        }
        
        return map;
    }//deleteProjectAlt()
    
    
    /**
     * Delete a Project Alt.
     * 
     * @param params A map contains:
     *     <ul>
     *       <li>id - int, id of a ProjectAlt object</li>
     *     </ul>
     * 
     * @return A map contains:
     *     <ul>
     *       <li>successful - a boolean value denoting if the operation succeeds</li>
     *       <li>reason - reason why operation failed (valid when successful==false)</li>
     *     </ul>
     */
    public Map deleteProjectAlt(Map params) {
        Map map = new HashMap();
        map.put("successful", false);
        
        try {
            Long id = new Long((String) params.get("id"));
            
            projectService.deleteProjectAlt(id);
            
            map.put("successful", true);
        } catch (Exception e) {
            e.printStackTrace();
            map.put("reason", e.getMessage());
            return map;
        }
        
        return map;
    }//deleteProjectAlt()
    
    
    /**
     * Set the project grading information
     * 
     * @param params A map contains:
     *     <ul>
     *       <li>altId - int, id of a ProjectAlt object</li>
     *       <li>critId - int, id of a Criteria object</li>
     *       <li>value - int, grading value</li>
     *     </ul>
     * 
     * @return A map contains:
     *     <ul>
     *       <li>successful - a boolean value denoting if the operation succeeds</li>
     *       <li>reason - reason why operation failed (valid when successful==false)</li>
     *     </ul>
     */
    public Map setGrading(Map params) {
        Map map = new HashMap();
        map.put("successful", false);
        
        try {
            Long altId = new Long((String) params.get("altId"));
            Long critId = new Long((String) params.get("critId"));
            int value = new Integer((String) params.get("value"));
            
            projectService.setGrading(altId, critId, value);
            
            map.put("successful", true);
        } catch (Exception e) {
            e.printStackTrace();
            map.put("reason", e.getMessage());
            return map;
        }
        
        return map;
    }//setGrading()
    
    
    /**
     * get footprints for a project alternative.<br>
     * 
     * @param params A map contains:
     *     <ul>
     *       <li>fpids - string, comma separated id list of the project alternative footprints</li>
     *     </ul>
     * 
     * @param 
     * 
     * @return A map contains:
     *     <ul>
     *       <li>successful - a boolean value denoting if the operation succeeds</li>
     *       <li>reason - reason why operation failed (valid when successful==false)</li>
     *       <li>footprints - a map contains pair of (id, coordinates)</li>
     *     </ul>
     */
    public Map getFootPrints(Map params) {
        Map map = new HashMap();
        map.put("successful", false);
        
        try {
            String fpids = (String) params.get("fpids");
            
            Map footprints = projectService.getFootprints(fpids);
            
            map.put("footprints", footprints);
            
            map.put("successful", true);
        } catch (Exception e) {
            e.printStackTrace();
            map.put("reason", e.getMessage());
            return map;
        }
        
        return map;
    }//getFootPrints()
    
    
    /**
     * Save the given footprint for a project alternative.<br>
     * 
     * @param params A map contains:
     *     <ul>
     *       <li>altId - int, id of the project alternative object</li>
     *       <li>shape - string, shape of the project alternative object,
     *                   "POINT"| "LINE" | "POLYGON"
     *       </li>
     *     </ul>
     * 
     * @param coordinates - double[][][], the footprint coordinates
     * 
     * @return A map contains:
     *     <ul>
     *       <li>successful - a boolean value denoting if the operation succeeds</li>
     *       <li>reason - reason why operation failed (valid when successful==false)</li>
     *       <li>fpid - int, id of the new created footprint</li>
     *     </ul>
     */
    public Map saveFootPrint(Map params, double[][][] coordinates) {
        Map map = new HashMap();
        map.put("successful", false);
        
        try {
            Long altId = new Long((String) params.get("altId"));
            String shape = (String) params.get("shape");
            
            Long fpid = projectService.saveFootprint(altId, coordinates, shape);
            
            map.put("fpid", fpid);
            
            map.put("successful", true);
        } catch (Exception e) {
            e.printStackTrace();
            map.put("reason", e.getMessage());
            return map;
        }
        
        return map;
    }//saveFootPrint()
    
    
    /**
     * Delete the given footprint.<br>
     * 
     * @param params A map contains:
     *     <ul>
     *       <li>fpid - int, id of the new created footprint</li>
     *     </ul>
     * 
     * @return A map contains:
     *     <ul>
     *       <li>successful - a boolean value denoting if the operation succeeds</li>
     *       <li>reason - reason why operation failed (valid when successful==false)</li>
     *     </ul>
     */
    public Map deleteFootPrint(Map params, double[][][] coordinates) {
        Map map = new HashMap();
        map.put("successful", false);
        
        try {
            Long fpid = new Long((String) params.get("fpid"));
            
            projectService.deleteFootPrint(fpid);
            
            map.put("fpid", fpid);
            
            map.put("successful", true);
        } catch (Exception e) {
            e.printStackTrace();
            map.put("reason", e.getMessage());
            return map;
        }
        
        return map;
    }//deleteFootPrint()
    
    
}//class ProjectAgent
