
<%@ taglib uri="http://jakarta.apache.org/struts/tags-bean" prefix="bean" %>
<%@ taglib uri="http://jakarta.apache.org/struts/tags-html" prefix="html" %>
<%@ taglib uri="http://jakarta.apache.org/struts/tags-logic" prefix="logic" %>
<%@ taglib uri="http://java.sun.com/jstl/fmt" prefix="fmt" %>
<%@ taglib uri="http://www.pgist.org/pgtaglib" prefix="pg" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>



<pg:fragment type="html">
	SD Criteria
</pg:fragment>
/*

criteriaAgent.getThemes
    Parameters:
        params - a Map contains:
            * cctId - int, the id of an CCT object
    Returns:
        a Map contains:
            * successful - a boolean value denoting if the operation succeeds
            * reason - reason why operation failed (valid when successful==false)
            * html - a HTML source segment. (Generated by /WEB-INF/jsp/criteria/criteriaAssoc_themes.jsp)
              The following variables are available for use in the jsp:
                  o cct - A CCT objects
                  o criteria - A list of Criteria objects
*/
<pg:fragment type="script">
		function getAvailableCriteria(themeId){
				CriteriaAgent.getAvailableCriteria({cctId: cctId, themeId: themeId}, {
				callback:function(data){
						if (data.successful){
							alert("getAvailableCriteria Successful");
						}
				},
				errorHandler:function(errorString, exception){ 
				alert("getAvailableCriteria Error: "+errorString+" "+exception);
				}
			});
		}
</pg:fragment>